project_id = "mrcfpbkoulldnkqzzprb"

[functions.send-email]
verify_jwt = false

[functions.track-email-open]
verify_jwt = false

[functions.ai-email-writer]
verify_jwt = false

[functions.inbound-email]
verify_jwt = false
